name: Build and Update Azure Container Instance
on:
  schedule:
    - cron: "0 1 * * *"  # Run daily at 1 AM UTC

jobs:
  build-and-update-container:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/USERNAME/REPOSITORY:latest .
          docker push ghcr.io/USERNAME/REPOSITORY:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update ACI with new image
        run: |
          az container create --resource-group myResourceGroup --name mycontainer --image ghcr.io/markd-bit/sentinel-log:latest --location myLocation --os-type Linux --cpu 1 --memory 2
          az container delete --resource-group myResourceGroup --name myOldContainer --yes

      - name: Send notification
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🐳 Azure Container Instance `mycontainer` has been updated to the latest image.
            🗑️ Old container instance `myOldContainer` has been removed.
