name: Check Base Image Update
on:
  schedule:
    - cron: "0 1 * * *"  # Schedule to run daily at 01:00 UTC
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main

env:
  image: ${{ vars.DOCKER_USERNAME }}/sentinel-log
  base-image: chaos.azurecr.io/sentinel-log:latest

jobs:
  check-base-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if update available
        id: check
        uses: markd-bit/docker-image-update-checker.yaml@main
        with:
          base-image: ${{ env.base-image }}
          image: ${{ env.image }}
          platforms: linux/amd64,linux/arm64
        env:
          DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}

      - if: steps.check.outputs.needs-updating == 'true'
        name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          push: false  # Don't push the image to Docker Hub
          tags: ${{ env.image }}:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - if: steps.check.outputs.needs-updating == 'true'
        name: Send Telegram Notification
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🐳 Base image ${{ env.base-image }} of ${{ env.image }} has been updated.
            ⚙️ Image rebuild is triggered.
            📚 Repository: [${{ github.repository }}](https://github.com/${{ github.repository }})
